name: learn-github-actions-from-main-yml
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
  pull_request:
    types: [opened, labeled, unlabeled, assigned, edited, reopened]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

  check-bats-version-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v